### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MichalBryxi** [dougfales/gpx#48]
Tried to use this gem for it's `GPX::GeoJSON` functionality, but found out that currently released version `1.0` does not have #38 in it. Would it be possible to release new version so that the `README.md` on `master` matches released version? Or just in general to prevent confusion.

**Comment by niborg** [comment]
Yes, that is a good idea! Unfortunately I don't have RubyGems credentials, see [here](https://github.com/dougfales/gpx/issues/44#issuecomment-1030727903). @dougfales what say you, can you cut a new release or otherwise can [grant me access as an owner of RubyGems](https://guides.rubygems.org/command-reference/#gem-owner)?

In the short term, I can to update the README to specify the master github branch.

**Comment by dougfales** [comment]
Hi @niborg, sorry for the delay, and thanks for offering to create a new release for me. I've added you as an owner, since I don't have much spare time these days. Please let me know if you need anything else from me. Thanks again!

**Comment by niborg** [comment]
OK v1.1.0 is out. Thank you @dougfales
